# Numpy Basics

If you don't have **numpy** installed, please install it from the terminal so you can continue
```bash
pip install numpy
```

Import numpy as np in the cell below

In [1]:
import numpy as np 

Create a numpy array from the list and print it

In [5]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


#write the code here

array = np.array(arr)
print(array)

 


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


Create a 2D numpy array from the list below and print it

In [9]:
list_of_lists = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
    [17, 18, 19, 20]
]

# write the code here

lista_2d = np.array(list_of_lists)
print(lista_2d)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


* Print the element with index 12 from the 1D array
* Print the elements from index 4 to index 15 from the 1D array

In [11]:
array[12]
array[4:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

* Print the element in row with index 3 and column index 2

In [12]:
lista_2d[3,2]

np.int64(15)

## Generating random numbers

Generate a 1D array with 15 random numbers that range from 5 to 500

In [13]:
random_numbers = np.random.randint(5, 500, size=15)
print(random_numbers)

[300 127 377 459  73 385   6 199 171 196 234 179 178 109 415]


Generate a 2D array with 5 rows, 4 columns per row with numbers that range from 10 to 1000

In [14]:
random_2d_array = np.random.randint(10, 1000, size=(5, 4))
print(random_2d_array)

[[699 709 896 946]
 [ 72 587 578 465]
 [394 216 553 740]
 [113 206 431 466]
 [ 12 372 348 317]]


## Operations with arrays

Generate an array of 10 elements with numbers from 1 to 100. Use the functions sum, max, min, mean to calculate the results

In [18]:
random_array = np.random.randint(1, 10, size=10)

array_sum = np.sum(random_array)
array_max = np.max(random_array)
array_min = np.min(random_array)
array_mean = np.mean(random_array)

print("Array:", random_array)
print("Sum:", array_sum)
print("Max:", array_max)
print("Min:", array_min)
print("Mean:", array_mean)

Array: [8 2 2 4 7 4 3 6 2 1]
Sum: 39
Max: 8
Min: 1
Mean: 3.9
